volumes:
  node-ipc:
  node-db:
services:
  cardano-node:
    image: ghcr.io/intersectmbo/cardano-node:9.1.1
    environment:
      NETWORK: ${NETWORK:-preview}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  ppp:
    build:
      context: .
      # These are the environment variables for dependencies,
      # grouped in one place for better version control.
      args:
        UBUNTU_VERSION: 22.04
        IOHK_LIBSODIUM: 'https://github.com/IntersectMBO/libsodium.git'
        IOHK_LIBSODIUM_GIT_REV: 1736ff8
        BTC_LIBSECP251: 'https://github.com/bitcoin-core/secp256k1.git'
        BTC_LIBSECP251_GIT_REV: ac83be33d0956faf6b7f61a60ab524ef7d6a473a
        CARDANO_CLI_VERSION: 9.2.1.0
        CABAL_VERSION: 3.12.1.0
        GHC_VERSION: 8.10.7
        HLS_VERSION: 2.2.0.0
        STYLISH_HASKELL_VERSION: 0.14.6.0
        NODE_VERSION: 22.4.1
    environment:
      NETWORK: ${NETWORK:-preview}
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace
      # Mounts cardano node socket
      - node-ipc:/root/.cardano/preview/ # for NETWORK=mainnet or set CARDANO_NODE_SOCKET_PATH explicitly

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
